Websocket server
OrganIA/organia-server pull request #96
Opened 2022-11-30 22:30 UTC by OkilSaber

2022-12-02 18:31 UTC, Tina-otoge requested changes

2022-12-02 18:31 UTC, Tina-otoge commented on app/__init__.py
> +    db.session.commit()
je pense que je préfère avoir ça dans le fichier de la table Role plutôt que dans le module global du projet

aussi, ne fait pas 
```python
Role(
**{
    'can_edit_users': False,
    'can_edit_hospitals': False,
    'can_edit_listings': False,
    ...
```
mais
```python
Role(
    can_edit_users=True,
    can_edit_hospitals=True,
    ...
```

`**` est la syntaxe pour "déconstruire" un dict et le passer comme en arguments à une fonction, par exemple
```python
d = {"reverse": True)
[1, 5, 2].sort(**d)
```
et
```python
[1, 5, 2].sort(reverse=True)
```
sont équivalent, mais dans le premier cas on créé un dict "pour rien", il faut donc s'en passer

2022-12-02 18:31 UTC, Tina-otoge commented on app/api/chats.py
> +        users = _create_users_list(data["users_ids"], auth_user)
bien vu 👍

2022-12-02 18:31 UTC, Tina-otoge commented on app/api/roles.py
> +    can_invite = bool
Hérite juste de `RoleSchema` au lieu de `Static` et met seulement `__ERROR_ON_UNFOUND__ = False`, vu qu'aucune des autres propriétés a changé

```python
class RoleUpdateSchema(RoleSchema):
    __ERROR_ON_UNFOUND__ = False
```

2022-12-02 18:31 UTC, Tina-otoge commented on app/api/roles.py
> +def get_roles():
auth.route inutile quand `auth_user` n'est pas en paramètre de la fonction

la protection des routes est activé sur tous les Blueprints (=routeurs) par défaut, sauf si on fait `Blueprint(auth=False)`

2022-12-02 18:31 UTC, Tina-otoge commented on app/api/roles.py
> +@auth.route()
auth.route...

2022-12-02 18:31 UTC, Tina-otoge commented on app/api/roles.py
> +    elif db.session.query(User).filter_by(role_id=role_id).all():
pas besoin d'appeler .all() ici, qui va aller chercher tous les users qui ont le rôle, hors on veut juste savoir si au moins 1 existe, donc utilise soit `.count()`, soit `.first()`, soit peut-êtrer que juste rien du tout suffit à checker si des membres existent, à tester

dans le cas où tu as des milliers d'users, tu vas tous les requêter alors que tu veux juste savoir si il y en a un

2022-12-02 18:31 UTC, Tina-otoge commented on app/api/roles.py
> +    elif db.session.query(User).filter_by(role_id=role_id).all():
pas besoin de "elif" ici, juste "if", vu que la branche précédante fini sur un raise ou un return, on va jamais "fall-through" jusqu'ici si le if d'au dessus est vrai

2022-12-02 18:31 UTC, Tina-otoge commented on app/api/roles.py
> +    else:
pareil ici pas besoin du else, la branche d'au dessus raise, donc elle termine forcément la fonction

retirer le else et dé-indenter ce qui suit

2022-12-02 18:31 UTC, Tina-otoge commented on app/api/users.py
> +    return auth_user.to_dict()
to_dict plus nécessaire

2022-12-02 18:31 UTC, Tina-otoge commented on app/api/users.py
> +    return db.session.get(User, user_id).to_dict()
to_dict

2022-12-02 18:31 UTC, Tina-otoge commented on app/api/websocket.py
> +                        "data": message.to_dict(),
vu que tu dépends de nouveau des `to_dict` ici, voir si tu peux faire en sorte de passer par la fonction `permissive_json` comme c'est fait dans les retours de route, qui elle va appeler `to_dict` tout seul

2022-12-02 18:31 UTC, Tina-otoge commented on app/api/websocket.py
> +    else:
else pas nécessaire parce que le if d'au dessus raise, retirer et dé_identer ce qui suit

2022-12-02 18:31 UTC, Tina-otoge commented on app/api/websocket.py
> +        return False
```python
return user_id in [user.id for user in chat.users]
```
ne jamais, jamais, jamais faire `if machin, return true, else, return false`, peu importe le langage, return directement ton booléen

2022-12-02 18:31 UTC, Tina-otoge commented on app/api/websocket.py
> +    message = Message(content=data["content"], chat=chat, sender=user)
ici data est une instance de `MessageCreateSchema` et pas un dict, donc tu ne peux pas faire `data["content"]` non ?

2022-12-02 18:31 UTC, Tina-otoge commented on app/db/models/__init__.py
> +from app.db.models.listing import Listing as Listing
imports absolus par normaux

2022-12-02 18:31 UTC, Tina-otoge commented on app/db/models/chat.py
> +        }
`to_dict` plus nécessaire, un `to_dict` générique est hérité depuis la base class de toutes les tables

2022-12-02 18:31 UTC, Tina-otoge commented on app/db/models/city.py
> +    def to_dict(self):
to dict

2022-12-02 18:31 UTC, Tina-otoge commented on app/db/models/listing.py
> +    def to_dict(self):
to di

2022-12-02 18:31 UTC, Tina-otoge commented on app/db/models/user.py
> +    role_id = sa.Column(sa.ForeignKey('roles.id'), nullable=False, default=1)
default=1 absolument pas fiable, aucune certitude que le role 1 soit le "default" et le 2 "admin"

ne met pas de default ici, et force que quand tu créés un user, le role par défaut soit celui qui s'appelle "default" (qui doit être cherché par son nom, pas par son ID)

2022-12-02 18:31 UTC, Tina-otoge commented on app/db/models/user.py
> +    def to_dict(self):
no more to dict pls

2022-12-02 18:31 UTC, Tina-otoge commented on app/errors.py
> +        self.description = msg
pas besoin de constructeur custom, y a déjà un constructeur qui fait exactement ce que tu écris là

2022-12-02 18:31 UTC, Tina-otoge commented on app/errors.py
> +        self.description = msg
non aux constructeurs

2022-12-02 18:31 UTC, Tina-otoge commented on app/utils/colors.py
> +        print(f"{color.value}{text}{Colors.Color.ENDC.value}")
ok c'est marrant

juste met pas de "any" c'est pas du TypeScript ici, met juste rien si tu type pas ta variable "text"

2022-12-02 18:31 UTC, Tina-otoge commented on app/utils/websocket_client.py
> +    def get_if_logged(self) -> bool:
`is_logged` au lieu de `get_if_logged`, c'est + clair sur ce que ça fait

2022-12-02 18:31 UTC, Tina-otoge commented on app/utils/websocket_manager.py
> +from typing import List, Union
`List` et `Union` servent à rien en Python 3.10

pour typer une liste tu peux faire `x: list[int]`

pour typer plusieurs types tu peux faire `x: int | bool | str`

2022-12-02 19:01 UTC, OkilSaber commented on app/api/roles.py
> +    can_invite = bool
J'ai déjà essayé de faire ça mais lorsque j'appelle ma route ça me met cette ÉNORME erreur:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54351241/205366520-8e56ec24-192f-46df-b85e-85157c9ef1b2.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54351241/205366574-8e189e14-3897-42df-99b6-71cc4b9741c3.png">

2022-12-02 19:12 UTC, OkilSaber commented on app/api/websocket.py
> +                        "data": message.to_dict(),
Le truc avec les websocket c'est que c'est juste une grosse string qui est reçue/renvoyée que je parse dans le server et le client. Du coup changer le type de réponse est pas possible et flask-sock c'est très basique et plutôt limité donc je suis obligé de faire le `.to_dict`.

2022-12-02 19:22 UTC, OkilSaber commented on app/api/websocket.py
> +    message = Message(content=data["content"], chat=chat, sender=user)
Si ça marche très bien et au contraire quand je faisais `data.content` je ne sais pas pourquoi mais ça ne marchait pas.

2022-12-02 19:29 UTC, OkilSaber commented on app/db/models/user.py
> +    role_id = sa.Column(sa.ForeignKey('roles.id'), nullable=False, default=1)
Par défaut on a mis que tous les utilisateurs étaient des administrateurs pour la facilité du dev et des présentations. Le rôle admin admin sera toujours 1 parce que c'est celui qui est toujours créé en premier lors de la création de la DB et il n'est pas censé être changé.

2022-12-02 19:34 UTC, OkilSaber commented on app/utils/websocket_manager.py
> +from typing import List, Union
Ça me faisait des erreurs du coup j'ai fait ça...

2022-12-02 19:50 UTC, Tina-otoge commented on app/api/websocket.py
> +    message = Message(content=data["content"], chat=chat, sender=user)
du coup c'est le typing qu'est pas bon, t'as un dict en paramètre pas une instance de la class que t'as mis

2022-12-02 19:51 UTC, Tina-otoge commented on app/api/websocket.py
> +                        "data": message.to_dict(),
qu'est-ce qui t'empêche d'appeler permissive_json sur ta fonction qui renvoie au client ?

2022-12-02 20:01 UTC, OkilSaber commented on app/api/websocket.py
> +                        "data": message.to_dict(),
Bah rien qui permet de dire "voilà quand tu fais send la data que tu la fais passer d'abord `permissive_json`"

2022-12-02 22:08 UTC, Tina-otoge commented on app/db/models/user.py
> +    role_id = sa.Column(sa.ForeignKey('roles.id'), nullable=False, default=1)
t'as pas de garantie que c'est lui qui est créé en premier si il y a des choses déjà dans la la DB
aussi tout simplement on set jamais l'ID à 1, ici tu assumes que l'ID généré automatiquement sera 1 mais rien ne te garantie que la DB va choisir cet ID, d'autant plus que le projet peut tourner sur n'importe quel DB supporté par SQLALchemy vu que c'est juste une variable d'environnement et ils peuvent avoir des comportements différents à ce niveau

2022-12-02 22:08 UTC, Tina-otoge commented on app/db/models/user.py
> +    role_id = sa.Column(sa.ForeignKey('roles.id'), nullable=False, default=1)
tu veux juste ajouter dans le constructeur d'un user, que si y a pas de role passé en paramètre du constructeur, tu fais une requête pour get le rôle qui s'appelle default (ou admin, n'importe)

```python
    def __init__(self, **kwargs):
        if password := kwargs.pop('password', None):
            self.save_password(password)
        if 'role' not in kwargs:
            kwargs["role"] = db.session.query(Role).filter_by(name="admin").first()
        super().__init__(**kwargs)
```
ou directement `Role.admin` si tu setup un raccourcvi comme le `User.admin` juste en dessous du constructeur

2022-12-02 22:08 UTC, Tina-otoge commented on app/utils/websocket_manager.py
> +from typing import List, Union
si ton Python en local est inférieur à 3.10 il te met un warning qui dit "tu peux faire ça que en 3.10" mais tu peux ignorer

tu peux checker la version utilisée en prod en regardant le Dockerfile

2022-12-04 11:13 UTC, Tina-otoge approved these changes
Retour pas fait : faire passer l'envoie de messages au client websocket par permissive_json, désormais tracké à part dans #100

2022-12-04 11:20 UTC, merged