Liver refactor
OrganIA/organia-server pull request #97
Opened 2022-12-02 16:54 UTC by NicolasYapobi

2022-12-02 18:56 UTC, Tina-otoge requested changes

2022-12-02 18:56 UTC, Tina-otoge commented on app/api/listings.py
> +    if listing.organ.value == "LIVER":
ne check pas avec le représentation en string de l'enum mais directement avec la clé de l'enum

2022-12-02 18:56 UTC, Tina-otoge commented on app/api/listings.py
> +    return organ
dans le cas où `listing.organ != Organ.Liver` tu crash parce que `organ.listing_id` et `organ.score` se feront sur un dict et pas un objet, vu que tu auras pas remplacé `organ = {}` par un objet

2022-12-02 18:56 UTC, Tina-otoge commented on app/api/livers.py
> +
saut de ligne en trop

2022-12-02 18:56 UTC, Tina-otoge commented on app/api/listings.py
> +bp = Blueprint('listings', auth=True)
pas besoin de mettre `'listings'`, passe `__name__` en premier paramètre et ça va trouver tout seul par rapport au nom du module/fichier (regarde "app/api/users.py" par exemple)

pas besoin de `auth=True`, c'est la valeur par défaut

2022-12-02 18:56 UTC, Tina-otoge commented on app/api/livers.py
> +# from pydantic import BaseModel
commentaire

2022-12-02 18:56 UTC, Tina-otoge commented on app/api/livers.py
> +bp = Blueprint('livers', auth=False)
remarque sur le blueprint pareil

2022-12-02 18:56 UTC, Tina-otoge commented on app/api/livers.py
> +bp = Blueprint('livers', auth=False)
je sais pas si on veut faire un blueprint pour les livers, si ?

on veut pas pouvoir éditer l'organe lié au patient depuis les même routes que celle qui édite un listing ?

plutôt que de d'avoir /api/livers, /api/hearts, /api/lungs, ...

2022-12-02 18:56 UTC, Tina-otoge commented on app/api/person.py
> +bp = Blueprint('persons', auth=True)
`__name__` et pas de `auth=True`, c'est le par défaut

2022-12-02 18:56 UTC, Tina-otoge commented on app/score/Kidney/DialyseScore.py
> +import datetime
nom de fichier pas bon

`app/scoring/kidney_dialyse.py` peut-être ?

dialyse c'est anglais même ? wikipédia dit "dialysis"

2022-12-02 18:56 UTC, Tina-otoge commented on app/score/Kidney/DialyseScore.py
> +    if listing_kidney.isDialyse is False:
isDialyse existe pas, est-ce is_under_dialysis ?

2022-12-02 18:56 UTC, Tina-otoge commented on app/score/Kidney/DialyseScore.py
> +    elif listing_kidney.isRetransplantation is False:
is_retransplantation

2022-12-02 18:56 UTC, Tina-otoge commented on app/score/Kidney/DialyseScore.py
> +        if listing_kidney.startDateDialyse is not None:
dialysis_start_date

2022-12-02 18:56 UTC, Tina-otoge commented on app/score/Kidney/DialyseScore.py
> +        listing_kidney.EndDateDialyse is not None
...

2022-12-02 18:56 UTC, Tina-otoge commented on app/score/Kidney/DialyseScore.py
> +        and listing_kidney.EndDateDialyse > listing_kidney.DateTransplantation
...

2022-12-02 18:56 UTC, Tina-otoge commented on app/score/Kidney/DialyseScore.py
> +        return (1 / 120) * getWaitingTime(receiver_listing, listing_kidney).days
changer toutes les variables pour utiliser celles qui existent en DB

changer le naming des fonctions pour quels respectent la PEP8

si `getScore` est le "main" pour chaque algo, peut-être avoir un seul entrypoint dans le module scoring qui puisse appeler n'importe quel algo

2022-12-02 18:56 UTC, Tina-otoge commented on app/score/Kidney/HLA_Age.py
> +from app.db.models import Listing, Person
c'est quoi HLA ? trouver un meilleur path

\+ naming fonctions

2022-12-02 18:56 UTC, Tina-otoge commented on app/score/Kidney/HLA_Age.py
> +    elif receiver.age >= 100:
pas besoin de elif vu qu'on fait un return, on peut juste if

2022-12-02 18:56 UTC, Tina-otoge commented on app/score/Kidney/HLA_Age.py
> +    elif receiver.age > 75:
elif -> if

2022-12-02 18:56 UTC, Tina-otoge commented on app/score/Kidney/KidneyScore.py
> +import math
`app/scoring/kidney.py`

ou alors peut-être garder tous ceux en rapport avec le kidney dans un dossier kidney, et pouvoir appeler le "main" directement depuis le module "kidney"

2022-12-02 18:56 UTC, Tina-otoge commented on app/score/Kidney/KidneyScore.py
> +def getHAge(receiver, receiver_listing, listing_kidney):
naming fonctions

2022-12-02 18:56 UTC, Tina-otoge commented on postman/OrganIA.postman_collection.json
>  {
y a une collection Postman que je tiens à jour dans `docs`, tu peux utiliser celle-la et la tenir à jour elle à la place ?

2022-12-02 18:56 UTC, Tina-otoge commented on postman/OrganIA.postman_collection.json
> +									"value": "7-2-678139cbfb87316fd71df494ab49b60733f046fdfa0a769e3d99a1d0528d21c6",
pas de token dans la collection ça dépend de chaque ordi

tu peux faire un préhook qui appelle la route de login et récupère le token, ou bien une variable dans la collection

2022-12-02 18:56 UTC, Tina-otoge commented on postman/OrganIA.postman_collection.json
> +									"value": "4-2-0fdc42590ce5d8de2de47fe4eeecb7bef1cab2a36ce94b3fe0cb1fa713caee97",
token

2022-12-02 18:56 UTC, Tina-otoge commented on postman/OrganIA.postman_collection.json
> +									"value": "7-2-678139cbfb87316fd71df494ab49b60733f046fdfa0a769e3d99a1d0528d21c6",
tokkkkk

2022-12-02 18:56 UTC, Tina-otoge commented on postman/OrganIA.postman_collection.json
> +							"raw": "{\r\n  \"first_name\": \"string\",\r\n  \"last_name\": \"string\",\r\n  \"birth_date\": \"2021-09-15\",\r\n  \"description\": \"string\",\r\n  \"abo\": \"A\",\r\n  \"rhesus\": \"+\",\r
déjà fix dans la collection dans `docs`

2022-12-02 18:56 UTC, Tina-otoge commented on postman/OrganIA.postman_collection.json
> +									"value": "1-1-d10ff213d81c60aba869175637ee3d4b46396ebadb49180ceb08f3c405b74730",
tokkkkk

2022-12-02 18:56 UTC, Tina-otoge commented on scripts/compose.sh
> +podman-compose up
`ln -sf `which podman-compose` ~/.local/bin/docker-compose`

2022-12-02 23:57 UTC, NicolasYapobi commented on app/score/Kidney/KidneyScore.py
> +import math
Compliqué en vue de toutes les fonctions qu'il faut pour lancer

2022-12-02 23:58 UTC, NicolasYapobi commented on postman/OrganIA.postman_collection.json
>  {
D'accord, je ferai attention à ça

2022-12-03 00:31 UTC, NicolasYapobi commented on app/score/Kidney/DialyseScore.py
> +        return (1 / 120) * getWaitingTime(receiver_listing, listing_kidney).days
A voir

2022-12-04 17:31 UTC, OkilSaber approved these changes

2022-12-04 17:32 UTC, merged